spring.application.name=gamifikasi
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/gamifikasi
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql:true
server.port=8081

# JWT Configuration
# Secret key: minimal 256-bit (32 bytes) diencoding Base64
jwt.secret=Z2FtaWZpa2FzaUpXVFNlY3JldEtleVN1cGVyU2VjdXJlMjAyNg==
jwt.expiration-ms=86400000
